TOP_DIR=..

DEMO_ID=0

NEM_XML=bypassnem.xml

GENERATED_PLATFORMS=platform1.xml platform2.xml platform3.xml platform4.xml

GENERATED_EVENTDAEMONS=          

GENERATED_GPSDLOCATIONAGENTS=    

GENERATED_MGENINPUTS=

GENERATED_ROUTINGCONFS=           

NO-%:
	touch $@

GENERATED_EXTRA=           \
 NO-host-emaneeventservice \
 NO-node-emaneeventd       \
 NO-node-emanetransportd   \
 NO-node-gpsd              \
 NO-node-routing

include ../rules.mk


